version: '3.9'
services:
  web:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000 # new
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=e^i)4f*ukztxa&n1@f@&u@@2pg5nq3n*#=3#tn6^alw-e$gr02"
    
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: