# Generated by Django 4.0.3 on 2022-03-26 17:39

import books.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='cover_url',
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='book/pdfs', validators=[books.validators.validate_pdf_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
