# Generated by Django 4.0.3 on 2022-03-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/<django.db.models.fields.UUIDField> cover/'),
        ),
    ]
