# Generated by Django 4.0.3 on 2022-03-20 18:42

import books.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='book/pdfs/', validators=[books.validators.validate_pdf_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
