# Generated by Django 4.0.3 on 2022-03-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_cover_book_cover_url_alter_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
    ]
